### PR TITLE
Outsource Entrez Gene logic to cognoma/genes

### LINKED ISSUE #23: Export a gene information table
Similar to how we have sample information in `samples.tsv`, it would be nice to create a table with gene information. The primary identifier is `entrez_gene_id`. Additional columns could be:
- `symbol`
- `name`
- `chromosome`
- `n_mutations` - number of mutated samples
- `median_expression` - median gene expression
- `mad_expression` - median absolute deviation of gene expression

I'm leaning towards a combined dataset for mutation and expression genes. But I could be convinced that splitting the datasets would be better.

We should probably get this information from entrez gene as @clairemcleod did in #12.

Labeling this issue a task awaiting a claimer.

### PR DESCRIPTION
**Pull request by dhimmel**
`0.genes-download.ipynb` is a notebook to download datasets from `cognoma/genes`. Update `2.TCGA-process.ipynb` to use the gene mapping guidelines in cognoma/genes#1. Remove `mapping/PANCAN-mutation/` since this mapping is now done in `2.TCGA-process.ipynb`.

Closes #23. Closes #30 by exporting gene info files in `2.TCGA-process.ipynb`.

### CODE REVIEW

**Comment by dhimmel** [comment]
Will update repo and commit info in `0.genes-download.ipynb` once cognoma/genes#1 is merged.

**Review by cgreene — APPROVED** [review]
Read both the new genes-download code and the changes to TCGA-process. Both seem reasonable in light of the new logic in the `genes` repository.

**Comment by dhimmel** [comment]
@cgreene could you take a look at the additional changes.

**Comment by cgreene** [comment]
Ok - reviewed commit d15f4c10c13fc67adb4352898acaafffd5200303 - do you want to check that the genes are correlated before averaging? They probably are... but I know the Troyanskaya Lab used to have some logic to only calculate the mean for genes that agreed after symbol mapping. I think Matt Hibbs first wrote it if I recall correctly.

**Comment by cgreene** [comment]
Reviewed commit eeba83d7604f45d1ae7c698ae61d44b7a867deaf and it LGTM :+1:

**Comment by cgreene** [comment]
My feelings are: full PR LGTM :+1: - one question. I don't think you need to address it now. You may want to consider it (maybe it's worth an issue)?

**Comment by dhimmel** [comment]
> do you want to check that the genes are correlated before averaging?

I agree that correlation is a good sanity check here. Given that only 39 genes had multiple expression measurements ([see this diff](https://github.com/cognoma/cancer-data/pull/32/commits/d15f4c10c13fc67adb4352898acaafffd5200303#diff-38ba94bbe504cccdff0a78dc181e1400)), I'm not too worried about any issues.

If anyone is worried just reply here or open and issue and I'll be happy to look into it further.

**Pull request merged**
