### PR TITLE
Add cancer-type codes to mapping

### PR DESCRIPTION
**Pull request by gwaybio**
from https://gdc.cancer.gov/resources-tcga-users/tcga-code-tables/tissue-source-site-codes

study name modified to match diseases.tsv

### CODE REVIEW

**Comment by dhimmel** [comment]
Let's move diseases.tsv to mapping

**Comment by gwaybio** [comment]
moved in 8fb25ee - updated directories in 13013be

**Review by dhimmel — APPROVED** [review]

**Comment by dhimmel** [comment]
This has a mistake. `downloads/diseases.tsv` should be moved to mapping, not the generated `data/diseases.tsv`.

**Review by dhimmel — CHANGES_REQUESTED** [review]
This has a mistake. `download/diseases.tsv` should be moved to mapping, not the generated `data/diseases.tsv`.

**Comment by gwaybio** [comment]
> This has a mistake. download/diseases.tsv should be moved to mapping, not the generated data/diseases.tsv.

My bad. I rebased and updated to change `diseases.tsv` download --> mapping

**Review by dhimmel — APPROVED** [review]
Looks good now. I will merge.

**Pull request merged**
