### PR TITLE
Map HiSeqV2 symbols to entrez gene IDs

### PR DESCRIPTION
**Pull request by dhimmel**
This is a temporary solution based on a mapping provided by @jingchunzhu [on the Xena Browser Google Group](https://groups.google.com/d/msg/ucsc-cancer-genomics-browser/uMsXgDwkkxg/eofxMaFGBAAJ).

The approach successfully converted all genes in the current `HiSeqV2` (see version info in `download/HiSeqV2.json`) into entrez gene ids.

Updates to HiSeqV2 may require a new mapping solution. Since the mapping isn't a permanent item in our processing pipeline, I added to a `mapping/HiSeqV2-genes` directory, rather than directly in the root directory.

### CODE REVIEW

**Comment by dhimmel** [comment]
For convenience, here's the [direct link to the notebook](https://github.com/dhimmel/cancer-data/blob/e87671b417b411f39a6881a05c1ade0261e0eae9/mapping/HiSeqV2-genes/map-HiSeqV2-genes.ipynb) that processes `unc.edu.f72bfbe6-411d-412e-aaab-1a2414e544ec.2146068.rsem.genes.normalized_results` to extract the symbol-ID mapping. And [here's the diff](https://github.com/cognoma/cancer-data/pull/8/files#diff-77658536bec871d5b60d50e8f969f816) for `2.TCGA-process.py`.

**Comment by dhimmel** [comment]
I should have mentioned in the commit message that this PR addresses part of #6.

**Comment by clairemcleod** [comment]
Reviewed, looks good. Based on my understanding of the Google Groups conversation, the Xena datasets should at some point include Entrez IDs natively?

**Comment by dhimmel** [comment]
> Based on my understanding of the Google Groups conversation, the Xena datasets should at some point include Entrez IDs natively?

@clairemcleod that's what it sounded like. I don't think they're planning to switch to entrez GeneIDs as their primary identifier, but maybe they would make the gene mapping an official output of their pipeline... that was my interpretation.

@clairemcleod would you like to merge? You can do a squash commit since their is only one commit and this will avoid an unnecessary merge commit.

**Pull request merged**
